[project]
name = "aiagent"
version = "0.1.0"
description = "Guided AI Agent project from Boot.dev"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autopep8>=2.3.2",
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]
